project:
  type: website
  output-dir: docs

website:
  title: "Kristina Glass"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resource.qmd
        text: Resources

format:
  html:
    theme:
      light: vapor
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

